name: MyPrueba
on:
  - push
jobs:
  build-test:
    runs-on: ubuntu-latest
    run: 
       vendor/bin/phpunit --migrate-configuration

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        env:
          TEST_NAME: Scarlett
        with:
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
      - name: Install composer dependencies
        run: 
           vendor/bin/phpunit --migrate-configuration
    
